name: insta_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8

  # Image handling
  cached_network_image: ^3.4.1
  image: ^4.1.7

  # Camera and permissions
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  app_settings: ^6.1.1
  image_picker: ^1.0.7 # 최신 버전으로 확인하고 추가하세요


  # State management
  provider: ^6.1.5

  # File system
  path: ^1.9.0
  path_provider: ^2.1.3
  local_image_provider: ^4.0.0

  # Firebase (updated to latest)
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6

  # Social login (flutter_facebook_login is deprecated)
  flutter_facebook_auth: ^7.1.2

  # UI components
  flutter_tags: ^1.0.0-nullsafety.1  # Keep original version

  # Reactive programming
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: VeganStyle
      fonts:
        - asset: assets/fonts/instafont.ttf
  assets:
    - assets/images/
