name: insta_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2 # SDK 버전이 명시되어 있으므로, local_image_provider 구버전과 호환성 문제가 있을 가능성이 매우 높습니다.

dependencies:
  flutter:
    sdk: flutter

  pdfx:
    git:
      url: https://github.com/ScerIO/packages.flutter
      ref: 8b105a7dfc6b90220c1d79fcb805fb764cab00c5
      path: packages/pdfx


  # UI and Icons
  cupertino_icons: ^1.0.8

  # Image handling
  cached_network_image: ^3.4.1
  image: ^4.1.7
  photo_manager: ^3.1.1
  transparent_image: ^2.0.1
  # Camera and permissions
  camera: ^0.11.1 # camera 패키지도 최신 버전으로 확인해보세요.
  permission_handler: ^12.0.0+1
  app_settings: ^6.1.1
  image_picker: ^1.0.7 # 로컬 이미지를 가져오는 데 이 패키지를 활용할 수 있습니다.


  # State management
  provider: ^6.1.5

  # File system
  path: ^1.9.0
  path_provider: ^2.1.3
  # local_image_provider: ^4.0.0 # 이 라인을 삭제하거나 주석 처리합니다.

  # Firebase (updated to latest)
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6

  # Social login (flutter_facebook_login is deprecated)
  flutter_facebook_auth: ^7.1.2

  # UI components
  flutter_tags: ^1.0.0-nullsafety.1

  # Reactive programming
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: VeganStyle
      fonts:
        - asset: assets/fonts/instafont.ttf
  assets:
    - assets/images/